###
// To get all inactive records (Draft records) from CAP service
GET http://localhost:4004/todo-admin-srv/ToDoLists?$filter=IsActiveEntity eq false
Content-Type: application/json

###
// Reqeust to get one specific Draft Record - Working Fine
GET http://localhost:4004/todo-admin-srv/ToDoLists(TaskID=6f8d7f6e-b93e-4d90-a0ba-8fa51caf6270,IsActiveEntity=false)
Content-Type: application/json

###
// Request to call the Entity Bound Action/Function import to activate the inactive record
POST http://localhost:4004/todo-admin-srv/ToDoLists(TaskID=2bff697c-e43c-47be-b114-72eb6b1234c0,IsActiveEntity=false)/AdminServices.draftActivate
Content-Type: application/json

{}

###  
// To call UnBound Action/Function import from the CAP Service - Working Fine
POST http://localhost:4004/v2/todo-admin-srv/aCalculate_Estimation()      
Content-Type: application/json  

{}

###
// To send a POST call to the CAP Service - Working Fine
POST http://localhost:4004/todo-admin-srv/ToDoLists
Content-Type: application/json

{
    "TaskDescription": "Task Description new 5555",
    "TargetDate": "2024-09-10",
    "Status": "Pending",
    "Priority": "4"
}

###
// To do a GET call to the CAP Service - Working Fine
GET http://localhost:4004/todo-admin-srv/ToDoLists
Content-Type: application/json